baseURL = 'https://matchaxnb.github.io/berlin-1121-slides/'
languageCode = 'en-us'
title = 'Berlin Netlify-sennder slides and demo'

theme = [ "reveal-hugo", "hugo-notice", "diary" ]


[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
transition = "slide"
transition_speed = "fast"
theme = "white"
template = "sennder"
custom_theme = "custom-theme.scss"
custom_theme_compile = true
center = false
reveal_cdn = "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.2.0"
[params.logo]
src = "sennder-logo-h.png"

